"""Import unmodified, attributed teaching media. Run from the project root.

ASL Signbank media: CC BY-NC-SA 4.0, personal/noncommercial edition only.
Ayush Thakur / Kaggle photographs: CC0 (metadata saved alongside this script).
No sign is generated by AI. The manifest records source URLs and SHA-256.
"""
from pathlib import Path
import hashlib, json, re, time, zipfile
import xml.etree.ElementTree as ET
from urllib.parse import urljoin
import requests

ROOT = Path(__file__).resolve().parents[1]
ASSETS = ROOT / 'app/src/main/assets'
MEDIA = ASSETS / 'signs'
MEDIA.mkdir(parents=True, exist_ok=True)
session = requests.Session()
session.headers['User-Agent'] = 'IrssaPersonalLearning/2.0 (educational media attribution)'

def get(url):
    for attempt in range(3):
        try:
            response = session.get(url, timeout=40)
            response.raise_for_status()
            return response
        except requests.RequestException:
            if attempt == 2: raise
            time.sleep(2)

entries = {e.find('CVE_VALUE').text: e.attrib['CVE_ID'] for e in ET.parse(ROOT/'tools/asl.ecv').findall('.//CV_ENTRY_ML')}
ones = ['ZERO','ONE','TWO','THREE','FOUR','FIVE','SIX','SEVEN','EIGHT','NINE','TEN','ELEVEN','TWELVE','THIRTEEN','FOURTEEN','FIFTEEN','SIXTEENrep','SEVENTEENrep','EIGHTEENrep','NINETEENrep']
special = {20:'TWENTYneut', 25:'TWENTY-FIVEup', 30:'THIRTYneut',40:'FORTYstr',50:'FIFTYneut'}
vocab = {'hello':'HELLO','thanks':'THANK-YOU','water':'WATER','friend':'FRIEND','book':'BOOK','happy':'HAPPY','school':'SCHOOL','love':'LOVEs'}
targets = {}
for n in range(0,51):
    gloss = special.get(n) or (ones[n] if n < 20 else ['','','TWENTY','THIRTY','FORTY'][n//10]+'-'+ones[n%10])
    targets[f'num_{n}'] = gloss
targets.update({f'vocab_{key}': value for key,value in vocab.items()})
manifest = []
for key, gloss in targets.items():
    entry_id = entries[gloss]
    page = f'https://aslsignbank.com/dictionary/gloss/{entry_id}.html'
    destination = MEDIA / f'{key}.mp4'
    html = get(page).text if not destination.exists() else ''
    match = re.search(r'<video[^>]+src=[\"\x27]([^\"\x27]+)', html)
    if not match and not destination.exists():
        # A missing source must remain visible, never replaced with a wrong sign.
        manifest.append(dict(id=key,file='',type='unavailable',source=page,author='ASL Signbank (2026)',license='CC BY-NC-SA 4.0',licenseUrl='https://creativecommons.org/licenses/by-nc-sa/4.0/',gloss=gloss,sha256=''))
        print('NO PUBLIC VIDEO',key,gloss,flush=True)
        continue
    url = urljoin(page,match.group(1)) if match else page
    if not destination.exists():
        content = get(url).content
        if b'ftyp' not in content[:32]: raise ValueError(f'Not an MP4: {url}')
        destination.write_bytes(content)
    manifest.append(dict(id=key, file=f'signs/{key}.mp4', type='video', source=page, download=url, author='Hochgesang, Crasborn & Lillo-Martin / ASL Signbank (2026)', license='CC BY-NC-SA 4.0', licenseUrl='https://creativecommons.org/licenses/by-nc-sa/4.0/', gloss=gloss, sha256=hashlib.sha256(destination.read_bytes()).hexdigest()))
    print(key,gloss,destination.stat().st_size,flush=True)
    time.sleep(0.1)

with zipfile.ZipFile(ROOT/'tools/asl-dataset.zip') as archive:
    names = [x for x in archive.namelist() if len(x.split('/'))==3 and x.lower().endswith(('.jpeg','.jpg','.png'))]
    for letter in 'abcdefghijklmnopqrstuvwxyz':
        candidates = sorted(x for x in names if x.split('/')[1]==letter)
        preferred = [x for x in candidates if 'hand1' in x and '_dif_seg_3_' in x]
        chosen = (preferred or candidates)[0]
        key = 'letter_'+letter
        destination = MEDIA / f'{key}.jpg'
        destination.write_bytes(archive.read(chosen))
        manifest.append(dict(id=key,file=f'signs/{key}.jpg',type='photo',source='https://www.kaggle.com/datasets/ayuraj/asl-dataset',author='Ayush Thakur / ASL Dataset',license='CC0 1.0',licenseUrl='https://creativecommons.org/publicdomain/zero/1.0/',original=chosen,sha256=hashlib.sha256(destination.read_bytes()).hexdigest()))

(ASSETS/'media_manifest.json').write_text(json.dumps(manifest,indent=2),encoding='utf-8')
print(f'Prepared {len(manifest)} attributed lesson assets.',flush=True)
